[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts = -v --tb=short
testpaths = products quotes catalog
filterwarnings =
    ignore::DeprecationWarning
