# Generated by Django 6.0.5 on 2026-05-19 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_self_owned', models.BooleanField(default=False, help_text='是否自有品牌')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dimension', models.CharField(blank=True, choices=[('TYPE', '按类型'), ('SPACE', '按空间'), ('ORIGIN', '按产地')], default='TYPE', max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('parent', 'name', 'dimension')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category_l1', models.CharField(choices=[('SEATING', 'Seating'), ('DESKS_WORKSTATIONS', 'Desks & Workstations'), ('TABLE', 'Table'), ('STORAGE', 'Storage'), ('ACCESSORIES', 'Accessories'), ('EDUCATION', 'Education')], default='SEATING', max_length=20)),
                ('category_l2', models.CharField(blank=True, choices=[('TASK_CHAIR', 'Task Chair'), ('EXECUTIVE_CHAIR', 'Executive Chair'), ('CONFERENCE_CHAIR', 'Conference Chair'), ('STOOL', 'Stool'), ('LOUNGE_CHAIR', 'Lounge Chair'), ('STACKING_CHAIR', 'Stacking Chair'), ('BENCH', 'Bench'), ('HEIGHT_ADJUSTABLE_DESK', 'Height Adjustable Desk'), ('FIXED_DESK', 'Fixed Desk'), ('WORKSTATION_CLUSTER', 'Workstation Cluster'), ('EXECUTIVE_DESK', 'Executive Desk'), ('CONFERENCE_TABLE', 'Conference Table'), ('COFFEE_TABLE', 'Coffee Table'), ('TRAINING_TABLE', 'Training Table'), ('DINING_TABLE', 'Dining Table'), ('FILING_CABINET', 'Filing Cabinet'), ('BOOKSHELF', 'Bookshelf'), ('LOCKER', 'Locker'), ('CREDENZA', 'Credenza'), ('MONITOR_ARM', 'Monitor Arm'), ('CABLE_MANAGEMENT', 'Cable Management'), ('DESK_LAMP', 'Desk Lamp'), ('WHITEBOARD', 'Whiteboard'), ('ACOUSTIC_PANEL', 'Acoustic Panel'), ('STUDENT_DESK', 'Student Desk'), ('LECTURE_CHAIR', 'Lecture Chair'), ('COLLABORATIVE_TABLE', 'Collaborative Table')], default='', max_length=40)),
                ('origin', models.CharField(choices=[('IMPORT', '进口'), ('DOMESTIC', '国产')], default='IMPORT', max_length=10)),
                ('lead_time', models.CharField(blank=True, choices=[('WITHIN_45D', '45天内'), ('2_4M_VIETNAM', '2-4月【越南】'), ('2_4M_MALAYSIA', '2-4月【马来西亚】'), ('4_6M_EU', '4-6月【荷兰/意大利/德国】')], default='', max_length=40)),
                ('pricing_mode', models.CharField(choices=[('MATRIX', '配置-价格映射表'), ('RULE', '基准价+加价规则')], default='MATRIX', max_length=10)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='仅 RULE 模式使用', max_digits=10, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, help_text='最低售价（列表展示）', max_digits=10, null=True)),
                ('length_mm', models.IntegerField(blank=True, help_text='长度(mm)', null=True)),
                ('width_mm', models.IntegerField(blank=True, help_text='宽度(mm)', null=True)),
                ('height_mm', models.IntegerField(blank=True, help_text='高度(mm)', null=True)),
                ('official_url', models.URLField(blank=True, default='', max_length=500)),
                ('material_album', models.JSONField(blank=True, default=list, help_text='可选材质图册（图片路径数组）')),
                ('model_3d_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='products.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('product', 'category')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', through='products.ProductCategory', to='products.category'),
        ),
        migrations.CreateModel(
            name='ProductConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=200)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('guide_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductConfigDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_key', models.CharField(help_text='维度键，如 frame_color_back', max_length=100)),
                ('dimension_label', models.CharField(help_text='展示名，如 框架颜色（背框）', max_length=100)),
                ('options', models.JSONField(default=list, help_text='[{"key":"P1","label":"P1"}, ...]')),
                ('parent_dimension', models.CharField(blank=True, default='', help_text='级联父维度 key（可空）', max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_dimensions', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('DESIGN', '设计资源'), ('TRAINING', '培训资料'), ('CERTIFICATE', '资质文件')], max_length=15)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='documents.document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_documents', to='products.product')),
            ],
            options={
                'ordering': ['relation_type', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500)),
                ('thumbnail_path', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_signature', models.CharField(help_text='配置组合稳定哈希（按 key 排序后 hash）', max_length=255)),
                ('config_attributes', models.JSONField(default=dict, help_text='{"frame_color_back":"P1", ...}')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_matrix', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_key', models.CharField(max_length=100)),
                ('option_key', models.CharField(max_length=100)),
                ('price_delta', models.DecimalField(decimal_places=2, help_text='正负皆可', max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='products_pr_code_4c2607_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['origin'], name='products_pr_origin_99ad63_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category_l1'], name='products_pr_categor_3021ba_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category_l1', 'category_l2'], name='products_pr_categor_46bdad_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['lead_time'], name='products_pr_lead_ti_00fcc8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productconfigdimension',
            unique_together={('product', 'dimension_key')},
        ),
        migrations.AlterUniqueTogether(
            name='productdocument',
            unique_together={('product', 'document')},
        ),
        migrations.AddIndex(
            model_name='productpricematrix',
            index=models.Index(fields=['product', 'config_signature'], name='products_pr_product_b5b81a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productpricematrix',
            unique_together={('product', 'config_signature')},
        ),
        migrations.AlterUniqueTogether(
            name='productpricerule',
            unique_together={('product', 'dimension_key', 'option_key')},
        ),
    ]
