# Generated by Django 6.0.5 on 2026-07-01 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diameter_mm',
            field=models.IntegerField(blank=True, help_text='直径(mm)，圆形用', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(blank=True, default='', help_text='形状：方形/圆形/L形/异形 等，可扩展', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_l2',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.CreateModel(
            name='ProductConfigPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='款式代码，如 WW / WH', max_length=100)),
                ('label', models.CharField(blank=True, default='', help_text='款式说明', max_length=200)),
                ('selections', models.JSONField(default=dict, help_text='预设选项组合 {"维度":"选项",...}')),
                ('is_default', models.BooleanField(default=False, help_text='是否默认配置')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_presets', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('product', 'code')},
            },
        ),
    ]
