# Generated by Django 6.0.5 on 2026-07-02 14:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='整单折扣（%），QT-6 取消单项折扣后仅用整单折扣', max_digits=5),
        ),
    ]
