# Generated by Django 6.0.4 on 2026-04-23 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('content_type', models.CharField(choices=[('PRODUCT', '产品'), ('CASE', '案例'), ('QUOTE', '报价单'), ('CATALOG', '产品图册')], max_length=10)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('password_hash', models.CharField(blank=True, default='', max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_access_count', models.IntegerField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='sharing.sharelink')),
            ],
        ),
        migrations.CreateModel(
            name='ClickTrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('object_id', models.IntegerField()),
                ('object_name', models.CharField(blank=True, default='', max_length=200)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='sharing.sharelink')),
            ],
        ),
    ]
