# Generated by Django 6.0.5 on 2026-05-19 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('DESIGN', '设计资源'), ('TRAINING', '培训资料'), ('CERTIFICATE', '资质文件')], max_length=15)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentfolder')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('doc_type', models.CharField(choices=[('DESIGN', '设计资源'), ('TRAINING', '培训资料'), ('CERTIFICATE', '资质文件')], max_length=15)),
                ('resource_type', models.CharField(choices=[('FILE', '文件'), ('RICH_TEXT', '富文本'), ('VIDEO', '视频'), ('AUDIO', '音频')], default='FILE', help_text='资源类型：文件/富文本/视频/音频', max_length=15)),
                ('content', models.TextField(blank=True, default='', help_text='富文本内容（resource_type=RICH_TEXT 时使用）')),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentfolder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
