# Generated by Django 6.0.5 on 2026-05-19 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('industry', models.CharField(choices=[('TECH_OFFICE', '科技/互联网办公'), ('FINANCE_OFFICE', '金融/保险/财税办公'), ('REALESTATE_OFFICE', '地产/建筑/设计院'), ('EDUCATION_OFFICE', '教育培训办公'), ('MEDICAL_OFFICE', '医疗/大健康办公'), ('MEDIA_OFFICE', '广告/文创/传媒办公'), ('MANUFACTURE_OFFICE', '制造/实业/工厂办公'), ('GOVERNMENT_OFFICE', '政府/国企/事业单位'), ('OTHER', '其他')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500)),
                ('thumbnail_path', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cases.case')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('case', 'product')},
            },
        ),
        migrations.AddField(
            model_name='case',
            name='products',
            field=models.ManyToManyField(blank=True, through='cases.CaseProduct', to='products.product'),
        ),
    ]
